server:
  host: "localhost"
  port: 8080
  grpc_port: 9090

storage:
  engine: "badger"
  data_path: "./data/badger"
  in_memory: false
  sync_writes: false
  value_log_gc: true
  gc_interval: "5m"
  wal:
    enabled: true
    threshold: 67108864  # 64MB
    max_files: 5
    fsync_threshold: 1000
  cache:
    enabled: true
    size: 10000
    ttl: "30m"
    cleanup_interval: "5m"

cluster:
  node_id: "node1"
  peers: []
  raft_port: 7000

logging:
  level: "info"
  format: "json"
  output: "stdout"
  enable_request_tracing: true
  enable_correlation_ids: true
  enable_database_logging: false
  enable_performance_log: false
  log_sampling: 0

metrics:
  enabled: true
  port: 2112

tracing:
  enabled: false
  service_name: "kvstore"
  service_version: "1.0.0"
  environment: "development"
  exporter_type: "console"  # console, jaeger, otlp
  jaeger_endpoint: "http://localhost:14268/api/traces"
  otlp_endpoint: "http://localhost:4318"
  sampling_ratio: 1.0