server:
  host: "localhost"
  port: 8080
  grpc_port: 9090

storage:
  engine: "badger"
  data_path: "./data/badger"
  in_memory: false
  sync_writes: false
  value_log_gc: true
  gc_interval: "5m"

cluster:
  node_id: "node1"
  peers: []
  raft_port: 7000

logging:
  level: "info"
  format: "json"
  output: "stdout"
  enable_request_tracing: true
  enable_correlation_ids: true
  enable_database_logging: false
  enable_performance_log: false
  log_sampling: 0

metrics:
  enabled: true
  port: 2112