version: '3.8'

# Production overrides for docker-compose.yml
# Usage: docker-compose -f docker-compose.yml -f docker-compose.prod.yml up

services:
  kvstore:
    restart: always
    environment:
      - KV_LOG_LEVEL=info
      - KV_LOG_FORMAT=json
      - KV_METRICS_ENABLED=true
      - KVSTORE_ENV=production
    deploy:
      replicas: 3
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.25'
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  prometheus:
    restart: always
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: '0.3'
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  grafana:
    restart: always
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD:-admin}
      - GF_SECURITY_SECRET_KEY=${GRAFANA_SECRET_KEY}
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_ANALYTICS_REPORTING_ENABLED=false
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: '0.3'
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  jaeger:
    restart: always
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: '0.3'
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  nginx:
    restart: always
    deploy:
      resources:
        limits:
          memory: 64M
          cpus: '0.1'
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # Remove development-only services
  health-monitor:
    deploy:
      replicas: 0  # Disable in production

volumes:
  kvstore_data:
    driver: local
  prometheus_data:
    driver: local
  grafana_data:
    driver: local