apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: kvstore-base
  annotations:
    config.kubernetes.io/local-config: "true"

resources:
  - namespace.yaml
  - serviceaccount.yaml
  - rbac.yaml
  - configmap.yaml
  - secret.yaml
  - service.yaml
  - service-headless.yaml
  - statefulset.yaml
  - servicemonitor.yaml
  - poddisruptionbudget.yaml
  - networkpolicy.yaml

configMapGenerator:
  - name: kvstore-config
    files:
      - config/config.yaml
      - config/logging.yaml
    options:
      disableNameSuffixHash: true

secretGenerator:
  - name: kvstore-secrets
    envs:
      - secrets/.env
    options:
      disableNameSuffixHash: true

images:
  - name: kvstore
    newName: ghcr.io/distributed-kvstore/kvstore
    newTag: latest

commonLabels:
  app.kubernetes.io/name: kvstore
  app.kubernetes.io/part-of: kvstore-cluster

commonAnnotations:
  config.kubernetes.io/origin: |
    configuredIn: kustomization.yaml
    configuredBy:
      apiVersion: builtin
      kind: HelmChartInflationGenerator

vars:
  - name: CLUSTER_SIZE
    objref:
      kind: ConfigMap
      name: kvstore-config
      apiVersion: v1
    fieldref:
      fieldpath: data.cluster_size
  - name: NAMESPACE
    objref:
      kind: Namespace
      name: kvstore
      apiVersion: v1
    fieldref:
      fieldpath: metadata.name

replacements:
  - source:
      kind: ConfigMap
      name: kvstore-config
      fieldPath: data.cluster_size
    targets:
      - select:
          kind: StatefulSet
          name: kvstore
        fieldPaths:
          - spec.replicas
        options:
          create: true

patchesStrategicMerge:
  - patches/resource-limits.yaml

patchesJson6902:
  - target:
      version: v1
      kind: Service
      name: kvstore-lb
    path: patches/service-annotations.yaml