apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: kvstore-production

namespace: kvstore

resources:
  - ../../base
  - hpa.yaml
  - monitoring.yaml
  - alerts.yaml
  - backup.yaml

images:
  - name: kvstore
    newName: ghcr.io/distributed-kvstore/kvstore
    newTag: v1.0.0

configMapGenerator:
  - name: kvstore-config-env
    literals:
      - ENVIRONMENT=production
      - LOG_LEVEL=INFO
      - CLUSTER_SIZE=5
      - REPLICATION_FACTOR=3
      - STORAGE_SIZE=100Gi
      - MONITORING_ENABLED=true
      - TRACING_ENABLED=true
      - SECURITY_ENABLED=true
      - TLS_ENABLED=true
    options:
      disableNameSuffixHash: true

commonLabels:
  environment: production
  criticality: high
  
commonAnnotations:
  managed-by: kustomize
  environment: production
  backup-required: "true"
  monitoring-required: "true"

patchesStrategicMerge:
  - patches/production-resources.yaml
  - patches/production-storage.yaml
  - patches/production-security.yaml
  - patches/production-affinity.yaml

patchesJson6902:
  - target:
      version: v1
      kind: StatefulSet
      name: kvstore
    path: patches/production-replicas.yaml
  - target:
      version: v1
      kind: Service
      name: kvstore-lb
    path: patches/production-service-annotations.yaml
  - target:
      version: v1
      kind: StatefulSet
      name: kvstore
    path: patches/production-security-context.yaml

replicas:
  - name: kvstore
    count: 5

# Production-specific configuration
patches:
  - target:
      kind: ConfigMap
      name: kvstore-config
    patch: |-
      - op: replace
        path: /data/log_level
        value: INFO
      - op: replace
        path: /data/cluster_size
        value: "5"
      - op: replace
        path: /data/replication_factor
        value: "3"
      - op: replace
        path: /data/tls_enabled
        value: "true"
      - op: replace
        path: /data/security_enabled
        value: "true"

# Resource requirements for production
transformers:
  - ../../transformers/production-resources.yaml
  - ../../transformers/production-security.yaml

# Generators for production-specific resources
generators:
  - backup-cronjob.yaml
  - monitoring-dashboard.yaml