apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: kvstore-dev

namespace: kvstore-dev

resources:
  - ../../base

images:
  - name: kvstore
    newName: ghcr.io/distributed-kvstore/kvstore
    newTag: dev-latest

configMapGenerator:
  - name: kvstore-config-env
    literals:
      - ENVIRONMENT=dev
      - LOG_LEVEL=DEBUG
      - CLUSTER_SIZE=3
      - REPLICATION_FACTOR=2
      - STORAGE_SIZE=10Gi
      - MONITORING_ENABLED=true
      - TRACING_ENABLED=true
    options:
      disableNameSuffixHash: true

commonLabels:
  environment: dev
  
commonAnnotations:
  managed-by: kustomize
  environment: dev

patchesStrategicMerge:
  - patches/dev-resources.yaml
  - patches/dev-storage.yaml
  - patches/dev-service.yaml

patchesJson6902:
  - target:
      version: v1
      kind: StatefulSet
      name: kvstore
    path: patches/dev-replicas.yaml
  - target:
      version: v1
      kind: Service
      name: kvstore-lb
    path: patches/dev-service-type.yaml

replicas:
  - name: kvstore
    count: 3

# Development-specific configuration
patches:
  - target:
      kind: ConfigMap
      name: kvstore-config
    patch: |-
      - op: replace
        path: /data/log_level
        value: DEBUG
      - op: replace
        path: /data/monitoring_enabled
        value: "true"
      - op: replace
        path: /data/tracing_enabled
        value: "true"

# Resource adjustments for development
transformers:
  - ../../transformers/dev-resources.yaml